### ISSUE TITLE
mmerspoon：一枚强大的可操作 OS X 系统的...勺子～

### ISSUE THREAD

**Issue by withlin** [EmilyQiRabbit/amazing-system-utils#1]
>mmerspoon：一枚强大的可操作 OS X 系统的...勺子～

勺子～？ 还是钩子？

**Comment by EmilyQiRabbit** [comment]
> > mmerspoon：一枚强大的可操作 OS X 系统的...勺子～
> 
> 勺子～？ 还是钩子？

spoon 不是勺子吗？这就是...我在开玩笑啦🤣～哈哈～

**Comment by EmilyQiRabbit** [comment]
> 勺子～？ 还是钩子？

spoon 不是勺子吗？这就是...我在开玩笑啦🤣～哈哈～
